spring:
  config:
    activate:
      on-profile: "prod"


cards:
  message: "Welcome to Bits&Bytes Bank cards related local APIs"
  contactDetails:
    name: "Matthias Kowalski - Software Engineer (PROD Lead)"
    email: "matthias.kowalski@worldwide.de"
  onCallSupport:
    - (+49) 999 999 999
