spring:
  config:
    activate:
      on-profile: "qa"


loans:
  message: "Welcome to Bits&Bytes Bank loans related local APIs"
  contactDetails:
    name: "Matthias Kowalski - Software Engineer (QA Lead)"
    email: "matthias.kowalski@worldwide.de"
  onCallSupport:
    - (+49) 999 999 999
